export const DEFAULT_TOAST_DURATION = 6000;
export const EXIT_DURATION = DEFAULT_TOAST_DURATION * 0.1;
export const DEFAULT_ROUNDNESS = 16;
export const GROUP_THRESHOLD = 4;
export const AUTOPILOT_EXPAND_DELAY = DEFAULT_TOAST_DURATION * 0.025;
export const AUTOPILOT_COLLAPSE_DELAY = DEFAULT_TOAST_DURATION - 2000;
