export const DEFAULT_TOAST_DURATION = 6000;
export const EXIT_DURATION = DEFAULT_TOAST_DURATION * 0.1;
export const DEFAULT_ROUNDNESS = 14;
export const GROUP_THRESHOLD = 4;
export const AUTOPILOT_EXPAND_DELAY = 220;
export const AUTOPILOT_COLLAPSE_DELAY = 3200;
